openapi: 3.0.3
info:
  title: Clippizo Payments API
  version: 1.0.0
  description: PayPal and SePay payment integration endpoints

paths:
  /api/checkout/sepay:
    post:
      summary: Initiate SePay checkout
      tags: [Checkout]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [plan]
              properties:
                plan:
                  type: string
                  enum: [pro, enterprise]
      responses:
        200:
          description: Checkout URL generated

  /api/checkout/paypal:
    post:
      summary: Initiate PayPal checkout
      tags: [Checkout]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [plan]
              properties:
                plan:
                  type: string
                  enum: [pro, enterprise]
      responses:
        200:
          description: PayPal order created

  /api/checkout/paypal/capture:
    post:
      summary: Capture PayPal payment
      tags: [Checkout]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [orderId]
              properties:
                orderId:
                  type: string
      responses:
        200:
          description: Payment captured

  /api/webhooks/sepay:
    post:
      summary: SePay IPN webhook
      tags: [Webhooks]
      responses:
        200:
          description: Webhook processed

  /api/webhooks/paypal:
    post:
      summary: PayPal webhook
      tags: [Webhooks]
      responses:
        200:
          description: Webhook processed

  /api/subscription:
    get:
      summary: Get subscription status
      tags: [Subscription]
      responses:
        200:
          description: Subscription details

  /api/payments:
    get:
      summary: Get payment history
      tags: [Payments]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Payment history
